# Overview {.unnumbered}

This course provides an introduction to Spatial Data Modelling for Population Science using R. It has been designed to be delivered in 15 hours of teaching, split into five sessions of 3 hours each, including breaks, practical examples and questions. This course provides an intuitive and practical explanation of methods, modelling frameworks and theories for analysing spatial data, as well as demographic and social processes represented in space. Spatial data have become ubiquitous. Data containing location have become increasingly common in both volume and frequency with the development and use of new sensor, satellite technilogy and GPS-based technologies, such as smartphones, social media platforms and contactless payment systems. At the same time, social and demographic processes occur within a geographic context that conditions or triggers their evolution. Therefore, these processes must be studied explicitly, considering the spatial context in which they take place. For these reasons, techniques that enable the analysis and modelling of spatial data are essential to understand demographic and social processes to inform policy and business decision-making.

## Aim

The objective of the course is to expose students to a variety of techniques for the analysis and modelling of spatial data. The course discusses and illustrates the types of spatial data and the challenges they present, introducing a range of modelling and analytical approaches that explicitly account for space. It also aims to develop programming skills in the R language. These skills are important for several reasons: programming is in high demand, it teaches logical and methodical thinking, and it allows ideas to be materialised into tangible products such as maps. The course also aims to introduce generative artificial intelligence through the use of ChatGPT for code writing, debugging and reasoning.

## Learning Outcomes

By the end of the module, students should be able to:

-   identify some key sources of spatial data and resources of spatial analysis and modelling tools;\
-   explain the advantages of taking spatial structure into account when analysing spatial data;\
-   apply a range of computer-based techniques for the analysis of spatial data, including mapping, correlation, kernel density estimation, spatial interaction modelling and spatial econometrics;\
-   apply appropriate analytical strategies to tackle the key methodological challenges facing spatial analysis -- spatial autocorrelation, heterogeneity, and ecological fallacy; and,\
-   select appropriate analytical tools for analysing specific spatial data sets to address emerging social issues facing the society.\

## Teaching Approach

The course combines lectures with a strong practical component and independent work. Each session will cover one of the following components:

-   Types of spatial data.\
-   Manipulation and visualisation of spatial data.\
-   Analysis of location data.\
-   Analysis of spatial relationship data.\
-   Models that capture spatial correlation.\

The course: - Introduces these techniques in an intuitive and applied manner rather than through theoretical mathematical or statistical derivations.\

-  Focuses on explaining when and why a technique is appropriate, followed by its application.\
-   Uses several practical examples based on real data and research questions.\
-   Is built around the R programming language and uses structured computational notebooks compiled in a book, including code with explanations that can be reused with other datasets.\
